FROM --platform=linux/amd64 ubuntu 

RUN apt update && apt -y upgrade && apt install -y gcc make g++ gcc-multilib g++-multilib gh git language-pack-ja grub-pc-bin xorriso mtools build-essential && update-locale LANG=ja_JP.UTF8